<?php

namespace App;

use App\Traits\DateFormatString;
use App\Traits\HashIdFields;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use DateFormatString;

    protected $fillable = ['body'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::deleting(function ($post){
            $post->postImages()->delete();
            $post->postVideos()->delete();
            $post->comments()->delete();
            $post->likes()->delete();
            $post->sharePosts()->delete();
        });
    }

    //region Relations
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function postImages()
    {
        return $this->hasMany(PostImage::class)->with('userImage');
    }

    public function postVideos()
    {
        return $this->hasMany(PostVideo::class);
    }

    public function comments()
    {
        return $this->morphMany(Comment::class, 'commentable');
    }

    public function likes()
    {
        return $this->morphMany(Like::class, 'likeable');
    }

    public function sharePosts()
    {
        return $this->hasMany(SharePost::class);
    }
    //endregion
}
